export interface DummyProduct {
  id: string;
  name: string;
  brand: string;
  sku: string;
  category: string;
  categorySlug: "laptops" | "printers" | "cartridges" | "accessories";
  price: number;
  originalPrice: number | null;
  stock: number;
  rating: number;
  reviews: number;
  badge: string | null;
  badgeColor?: string;
  images: string[];
  description: string;
  specs: { label: string; value: string }[];
  relatedIds?: string[];
}

export const PRODUCTS: DummyProduct[] = [
  // ── LAPTOPS ─────────────────────────────────────────────────────────────────
  {
    id: "1",
    relatedIds: ["20", "21", "22", "31"],
    name: 'Dell Latitude 5540 15.6" Core i5',
    brand: "Dell",
    sku: "DELL-LAT-5540-I5",
    category: "Laptops",
    categorySlug: "laptops",
    price: 89000,
    originalPrice: 98000,
    stock: 5,
    rating: 4.7,
    reviews: 86,
    badge: "New",
    badgeColor: "bg-blue-600 text-white",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Dell+Latitude+5540"],
    description:
      'The Dell Latitude 5540 is a premium 15.6" business laptop powered by Intel Core i5-1335U. Built to MIL-SPEC durability standards with a Full HD IPS display, 512GB NVMe SSD, and enterprise security features. Trusted by businesses across Kenya.',
    specs: [
      { label: "Processor", value: "Intel Core i5-1335U (10 cores)" },
      { label: "RAM", value: "16GB DDR4 3200MHz" },
      { label: "Storage", value: "512GB NVMe SSD" },
      { label: "Display", value: '15.6" FHD 1920×1080 IPS Anti-glare' },
      { label: "Battery", value: "Up to 10 hours" },
      { label: "OS", value: "Windows 11 Pro" },
      { label: "Weight", value: "1.78 kg" },
      { label: "Warranty", value: "1 Year Dell ProSupport" },
    ],
  },
  {
    id: "2",
    relatedIds: ["20", "21", "22", "23"],
    name: "Lenovo ThinkPad E14 AMD Ryzen 5",
    brand: "Lenovo",
    sku: "LNV-TPE14-R5",
    category: "Laptops",
    categorySlug: "laptops",
    price: 72000,
    originalPrice: 82000,
    stock: 8,
    rating: 4.5,
    reviews: 41,
    badge: "Sale",
    badgeColor: "bg-brand text-brand-foreground",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=ThinkPad+E14"],
    description:
      'ThinkPad E14 Gen 4 — AMD Ryzen 5 powered, MIL-SPEC tested, spill-resistant keyboard, and crisp 14" FHD IPS display. The go-to business laptop for professionals who demand reliability.',
    specs: [
      { label: "Processor", value: "AMD Ryzen 5 5625U (6 cores)" },
      { label: "RAM", value: "8GB DDR4 (expandable to 16GB)" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '14" FHD IPS Anti-glare' },
      { label: "Battery", value: "Up to 9.5 hours" },
      { label: "OS", value: "Windows 11 Home" },
      { label: "Weight", value: "1.61 kg" },
      { label: "Warranty", value: "1 Year Lenovo" },
    ],
  },
  {
    id: "3",
    relatedIds: ["20", "21", "22", "23"],
    name: 'HP EliteBook 840 G9 14" Core i7',
    brand: "HP",
    sku: "HP-EB840-G9-I7",
    category: "Laptops",
    categorySlug: "laptops",
    price: 115000,
    originalPrice: 128000,
    stock: 4,
    rating: 4.9,
    reviews: 62,
    badge: "Best Seller",
    badgeColor: "bg-brand text-brand-foreground",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+EliteBook+840+G9"],
    description:
      "HP EliteBook 840 G9 — the executive flagship. Intel Core i7, 32GB DDR5, 1TB SSD, HP Sure View privacy screen and Wolf Security. The benchmark for enterprise laptops in Kenya.",
    specs: [
      { label: "Processor", value: "Intel Core i7-1255U (10 cores)" },
      { label: "RAM", value: "32GB DDR5" },
      { label: "Storage", value: "1TB NVMe SSD" },
      { label: "Display", value: '14" FHD IPS HP Sure View' },
      { label: "Battery", value: "Up to 12 hours" },
      { label: "OS", value: "Windows 11 Pro" },
      { label: "Weight", value: "1.38 kg" },
      { label: "Security", value: "HP Wolf Security, TPM 2.0" },
    ],
  },
  {
    id: "4",
    relatedIds: ["20", "22", "31", "32"],
    name: 'ASUS VivoBook 15 Core i3 15.6"',
    brand: "ASUS",
    sku: "ASUS-VB15-I3",
    category: "Laptops",
    categorySlug: "laptops",
    price: 48000,
    originalPrice: 55000,
    stock: 14,
    rating: 4.3,
    reviews: 109,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=ASUS+VivoBook+15"],
    description:
      "Slim, stylish, and budget-friendly. ASUS VivoBook 15 with Intel Core i3, full-HD display, and a fingerprint reader. Perfect for students and home-office use in Kenya.",
    specs: [
      { label: "Processor", value: "Intel Core i3-1115G4" },
      { label: "RAM", value: "8GB DDR4" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '15.6" FHD NanoEdge' },
      { label: "Battery", value: "Up to 8 hours" },
      { label: "OS", value: "Windows 11 Home" },
      { label: "Weight", value: "1.8 kg" },
      { label: "Extras", value: "Fingerprint reader, NumberPad" },
    ],
  },
  {
    id: "5",
    relatedIds: ["20", "22", "31", "23"],
    name: "HP 255 G8 AMD Ryzen 3 3250U",
    brand: "HP",
    sku: "HP-255-G8-R3",
    category: "Laptops",
    categorySlug: "laptops",
    price: 52000,
    originalPrice: 58000,
    stock: 12,
    rating: 4.4,
    reviews: 134,
    badge: "Popular",
    badgeColor: "bg-blue-600 text-white",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+255+G8"],
    description:
      "HP 255 G8 — best value business laptop in Kenya. AMD Ryzen 3 processor, 8GB RAM, and a full-HD display. Reliable, portable, and built for daily professional use.",
    specs: [
      { label: "Processor", value: "AMD Ryzen 3 3250U (2 cores)" },
      { label: "RAM", value: "8GB DDR4" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '15.6" FHD Anti-glare' },
      { label: "Battery", value: "Up to 8.5 hours" },
      { label: "OS", value: "Windows 11 Home" },
      { label: "Weight", value: "1.74 kg" },
      { label: "Warranty", value: "1 Year HP" },
    ],
  },
  {
    id: "6",
    relatedIds: ["20", "21", "22", "23"],
    name: "HP Pavilion 15 Core i5 12th Gen",
    brand: "HP",
    sku: "HP-PAV15-I5-12",
    category: "Laptops",
    categorySlug: "laptops",
    price: 68000,
    originalPrice: null,
    stock: 10,
    rating: 4.6,
    reviews: 88,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+Pavilion+15"],
    description:
      "HP Pavilion 15 with 12th Gen Intel Core i5 — balanced performance, vibrant display, and long battery life in a modern silver chassis. A great all-rounder for work and home.",
    specs: [
      { label: "Processor", value: "Intel Core i5-1235U (10 cores)" },
      { label: "RAM", value: "8GB DDR4" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Display", value: '15.6" FHD IPS' },
      { label: "Battery", value: "Up to 9 hours" },
      { label: "OS", value: "Windows 11 Home" },
      { label: "Weight", value: "1.74 kg" },
      { label: "GPU", value: "Intel Iris Xe Graphics" },
    ],
  },
  {
    id: "7",
    relatedIds: ["21", "23", "32", "22"],
    name: 'MacBook Air M2 13" 8GB/256GB',
    brand: "Apple",
    sku: "APPLE-MBA-M2-8",
    category: "Laptops",
    categorySlug: "laptops",
    price: 148000,
    originalPrice: 162000,
    stock: 3,
    rating: 5.0,
    reviews: 204,
    badge: "Hot Deal",
    badgeColor: "bg-red-500 text-white",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=MacBook+Air+M2"],
    description:
      "Apple MacBook Air M2 — fanless, featherlight, up to 18 hours battery. The M2 chip delivers desktop-class performance in the thinnest MacBook ever made.",
    specs: [
      { label: "Chip", value: "Apple M2 (8-core CPU, 8-core GPU)" },
      { label: "RAM", value: "8GB Unified Memory" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '13.6" Liquid Retina, 2560×1664' },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "OS", value: "macOS Ventura" },
      { label: "Weight", value: "1.24 kg" },
      { label: "Ports", value: "2× USB-C (Thunderbolt), MagSafe 3, 3.5mm" },
    ],
  },
  {
    id: "24",
    relatedIds: ["20", "21", "22", "31"],
    name: "Lenovo IdeaPad 3 AMD Ryzen 5 5500U",
    brand: "Lenovo",
    sku: "LNV-IP3-R5-5500",
    category: "Laptops",
    categorySlug: "laptops",
    price: 62000,
    originalPrice: 70000,
    stock: 9,
    rating: 4.5,
    reviews: 78,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Lenovo+IdeaPad+3"],
    description:
      "Lenovo IdeaPad 3 — AMD Ryzen 5 performance for everyday use. Backlit keyboard, Wi-Fi 6, and a 15.6\" FHD display. A well-rounded laptop at a competitive price.",
    specs: [
      { label: "Processor", value: "AMD Ryzen 5 5500U (6 cores)" },
      { label: "RAM", value: "8GB DDR4 (expandable)" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Display", value: '15.6" FHD IPS Anti-glare' },
      { label: "Battery", value: "Up to 7.5 hours" },
      { label: "OS", value: "Windows 11 Home" },
      { label: "Weight", value: "1.65 kg" },
      { label: "Extras", value: "Backlit keyboard, Wi-Fi 6" },
    ],
  },

  // ── PRINTERS ─────────────────────────────────────────────────────────────────
  {
    id: "8",
    relatedIds: ["14", "15", "16", "31"],
    name: "HP LaserJet Pro M404n Mono",
    brand: "HP",
    sku: "HP-LJ-M404N",
    category: "Printers",
    categorySlug: "printers",
    price: 28500,
    originalPrice: 33000,
    stock: 12,
    rating: 4.8,
    reviews: 124,
    badge: "Best Seller",
    badgeColor: "bg-brand text-brand-foreground",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+LaserJet+M404n"],
    description:
      "HP LaserJet Pro M404n — blazing 40ppm monochrome output with built-in Ethernet. 80,000-page monthly duty cycle. The office workhorse trusted by Kenyan businesses.",
    specs: [
      { label: "Print Speed", value: "Up to 40 ppm" },
      { label: "Resolution", value: "1200 × 1200 dpi" },
      { label: "Connectivity", value: "Ethernet, USB 2.0" },
      { label: "Duty Cycle", value: "Up to 80,000 pages/month" },
      { label: "Paper Capacity", value: "350 sheets" },
      { label: "Duplex", value: "Manual" },
      { label: "Weight", value: "7.44 kg" },
    ],
  },
  {
    id: "9",
    relatedIds: ["31", "21"],
    name: "Canon PIXMA G2410 Ink Tank MFP",
    brand: "Canon",
    sku: "CANON-G2410",
    category: "Printers",
    categorySlug: "printers",
    price: 19500,
    originalPrice: 22500,
    stock: 20,
    rating: 4.6,
    reviews: 57,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Canon+PIXMA+G2410"],
    description:
      "Canon PIXMA G2410 — refillable ink tank means ultra-low cost per page. Print, copy, and scan at home or the office. Up to 7,600 black pages from one ink refill.",
    specs: [
      { label: "Functions", value: "Print, Copy, Scan" },
      { label: "Print Speed", value: "8.8 ipm (B&W), 5 ipm (Colour)" },
      { label: "Resolution", value: "4800 × 1200 dpi" },
      { label: "Connectivity", value: "USB 2.0" },
      { label: "Black Yield", value: "~7,600 pages" },
      { label: "Colour Yield", value: "~7,700 pages" },
    ],
  },
  {
    id: "10",
    relatedIds: ["29", "31"],
    name: "Epson EcoTank L3250 Wi-Fi AIO",
    brand: "Epson",
    sku: "EPS-L3250",
    category: "Printers",
    categorySlug: "printers",
    price: 24000,
    originalPrice: 27500,
    stock: 15,
    rating: 4.7,
    reviews: 98,
    badge: "Popular",
    badgeColor: "bg-blue-600 text-white",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Epson+EcoTank+L3250"],
    description:
      "Epson EcoTank L3250 — print wirelessly from your phone via the Epson Smart Panel app. Enough ink for 7,500 colour pages included in-box. No cartridge stress, ever.",
    specs: [
      { label: "Functions", value: "Print, Copy, Scan" },
      { label: "Connectivity", value: "Wi-Fi, Wi-Fi Direct, USB" },
      { label: "Print Speed", value: "10 ipm (B&W), 5 ipm (Colour)" },
      { label: "Resolution", value: "5760 × 1440 dpi" },
      { label: "Black Yield", value: "~4,500 pages" },
      { label: "Colour Yield", value: "~7,500 pages" },
    ],
  },
  {
    id: "11",
    relatedIds: ["16", "14", "31"],
    name: "HP Color LaserJet Pro M479fdw",
    brand: "HP",
    sku: "HP-CLJP-M479FDW",
    category: "Printers",
    categorySlug: "printers",
    price: 62000,
    originalPrice: 72000,
    stock: 6,
    rating: 4.8,
    reviews: 44,
    badge: "Sale",
    badgeColor: "bg-brand text-brand-foreground",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+Color+LJ+M479"],
    description:
      "HP Color LaserJet Pro M479fdw — all-in-one colour laser with fax, auto duplex, and Wi-Fi. 28ppm in full colour. The ideal machine for marketing and design offices.",
    specs: [
      { label: "Functions", value: "Print, Copy, Scan, Fax" },
      { label: "Print Speed", value: "28 ppm (colour & mono)" },
      { label: "Resolution", value: "600 × 600 dpi" },
      { label: "Connectivity", value: "Wi-Fi, Ethernet, USB" },
      { label: "Paper Capacity", value: "300 sheets" },
      { label: "Duplex", value: "Automatic" },
    ],
  },
  {
    id: "12",
    relatedIds: ["28", "31"],
    name: "Brother HL-L2350DW Wi-Fi Laser",
    brand: "Brother",
    sku: "BRO-HLL2350DW",
    category: "Printers",
    categorySlug: "printers",
    price: 18500,
    originalPrice: 21000,
    stock: 22,
    rating: 4.5,
    reviews: 81,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Brother+HL-L2350DW"],
    description:
      "Brother HL-L2350DW — compact wireless monochrome laser printer. Auto duplex printing and mobile printing via Wi-Fi Direct. A favourite for home offices across Kenya.",
    specs: [
      { label: "Print Speed", value: "Up to 32 ppm" },
      { label: "Resolution", value: "2400 × 600 dpi" },
      { label: "Connectivity", value: "Wi-Fi, Wi-Fi Direct, USB" },
      { label: "Duplex", value: "Automatic" },
      { label: "Paper Capacity", value: "250 sheets" },
      { label: "Weight", value: "7.5 kg" },
    ],
  },
  {
    id: "13",
    relatedIds: ["18", "19", "31"],
    name: "Canon imageCLASS LBP6030 Laser",
    brand: "Canon",
    sku: "CANON-LBP6030",
    category: "Printers",
    categorySlug: "printers",
    price: 14500,
    originalPrice: 16500,
    stock: 30,
    rating: 4.3,
    reviews: 136,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Canon+LBP6030"],
    description:
      "Canon imageCLASS LBP6030 — compact and affordable mono laser for home and small offices. Quick first print, silent mode, and low running costs.",
    specs: [
      { label: "Print Speed", value: "Up to 18 ppm" },
      { label: "Resolution", value: "2400 × 600 dpi" },
      { label: "Connectivity", value: "USB 2.0" },
      { label: "Paper Capacity", value: "150 sheets" },
      { label: "First Print", value: "7.8 seconds" },
      { label: "Weight", value: "4.6 kg" },
    ],
  },
  {
    id: "25",
    relatedIds: ["14", "15", "31"],
    name: "HP LaserJet Pro M15w Wi-Fi Mono",
    brand: "HP",
    sku: "HP-LJ-M15W",
    category: "Printers",
    categorySlug: "printers",
    price: 13500,
    originalPrice: 15500,
    stock: 25,
    rating: 4.4,
    reviews: 91,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+LaserJet+M15w"],
    description:
      "HP LaserJet Pro M15w — the world's smallest laser printer. Print wirelessly from any device via Wi-Fi. Compact enough for any desk, fast enough for any office.",
    specs: [
      { label: "Print Speed", value: "Up to 19 ppm" },
      { label: "Resolution", value: "600 × 600 dpi" },
      { label: "Connectivity", value: "Wi-Fi, USB" },
      { label: "Paper Capacity", value: "150 sheets" },
      { label: "Duty Cycle", value: "Up to 8,000 pages/month" },
      { label: "Weight", value: "4.71 kg" },
    ],
  },
  {
    id: "26",
    relatedIds: ["27", "31"],
    name: "Ricoh SP 150w Wireless Laser",
    brand: "Ricoh",
    sku: "RICOH-SP150W",
    category: "Printers",
    categorySlug: "printers",
    price: 14000,
    originalPrice: 16000,
    stock: 18,
    rating: 4.3,
    reviews: 54,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Ricoh+SP+150w"],
    description:
      "Ricoh SP 150w — compact wireless laser printer with a low total cost of ownership. High-yield toner available. Simple setup and reliable daily performance.",
    specs: [
      { label: "Print Speed", value: "Up to 22 ppm" },
      { label: "Resolution", value: "1200 × 600 dpi" },
      { label: "Connectivity", value: "Wi-Fi, USB 2.0" },
      { label: "Paper Capacity", value: "150 sheets" },
      { label: "Duty Cycle", value: "Up to 10,000 pages/month" },
      { label: "Weight", value: "5.2 kg" },
    ],
  },

  // ── CARTRIDGES ───────────────────────────────────────────────────────────────
  {
    id: "14",
    relatedIds: ["8", "25"],
    name: "HP 85A Black Toner (CE285A) Original",
    brand: "HP",
    sku: "HP-CE285A",
    category: "Cartridges",
    categorySlug: "cartridges",
    price: 5500,
    originalPrice: 6500,
    stock: 60,
    rating: 4.8,
    reviews: 317,
    badge: "Best Seller",
    badgeColor: "bg-brand text-brand-foreground",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+85A+Toner"],
    description:
      "HP 85A Original Black LaserJet Toner — engineered for HP LaserJet Pro P1102, M1132, M1212nf MFP. ~1,600 page yield. Consistent, sharp black prints every single time.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "~1,600 pages @ 5% coverage" },
      { label: "Compatible With", value: "HP LJ Pro P1102, M1132, M1212nf" },
      { label: "Part Number", value: "CE285A" },
      { label: "Type", value: "Original HP" },
    ],
  },
  {
    id: "15",
    relatedIds: ["8", "25"],
    name: "HP 12A Black Toner (Q2612A) Original",
    brand: "HP",
    sku: "HP-Q2612A",
    category: "Cartridges",
    categorySlug: "cartridges",
    price: 5000,
    originalPrice: 5800,
    stock: 45,
    rating: 4.7,
    reviews: 228,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+12A+Toner"],
    description:
      "HP 12A Original LaserJet Toner — the classic workhorse for HP LaserJet 1010, 1012, 1015, 1018, 1020, and 3050 series. ~2,000 page yield. Reliable office performance.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "~2,000 pages @ 5% coverage" },
      { label: "Compatible With", value: "HP LJ 1010, 1012, 1015, 1018, 1020, 3050" },
      { label: "Part Number", value: "Q2612A" },
      { label: "Type", value: "Original HP" },
    ],
  },
  {
    id: "16",
    relatedIds: ["8", "11"],
    name: "HP 151A Black LaserJet Toner (W1510A)",
    brand: "HP",
    sku: "HP-W1510A",
    category: "Cartridges",
    categorySlug: "cartridges",
    price: 13000,
    originalPrice: null,
    stock: 20,
    rating: 4.8,
    reviews: 67,
    badge: "New",
    badgeColor: "bg-blue-600 text-white",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+151A+Toner"],
    description:
      "HP 151A Black Original LaserJet Toner (W1510A) — for HP LaserJet Pro 4001, 4002 and MFP 4101, 4102 series. ~3,500 page yield. Genuine HP quality, no compromise.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "~3,500 pages @ 5% coverage" },
      { label: "Compatible With", value: "HP LJ Pro 4001n/dn, MFP 4101fdw" },
      { label: "Part Number", value: "W1510A" },
      { label: "Type", value: "Original HP" },
    ],
  },
  {
    id: "17",
    name: "Samsung MLT-D101S Black Toner",
    brand: "Samsung",
    sku: "SAM-MLT-D101S",
    category: "Cartridges",
    categorySlug: "cartridges",
    price: 10000,
    originalPrice: 12000,
    stock: 18,
    rating: 4.6,
    reviews: 142,
    badge: "Hot Deal",
    badgeColor: "bg-red-500 text-white",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Samsung+MLT-D101S"],
    description:
      "Samsung MLT-D101S Black Original Toner — for Samsung ML-2160, ML-2165W, SCX-3400, SCX-3405 series. ~1,500 page yield. Genuine Samsung quality, widely available in Kenya.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "~1,500 pages @ 5% coverage" },
      { label: "Compatible With", value: "Samsung ML-2160, ML-2165W, SCX-3400/3405" },
      { label: "Part Number", value: "MLT-D101S/ELS" },
      { label: "Type", value: "Original Samsung" },
    ],
  },
  {
    id: "18",
    relatedIds: ["13"],
    name: "Canon 725 Black Toner Cartridge",
    brand: "Canon",
    sku: "CANON-CRG725",
    category: "Cartridges",
    categorySlug: "cartridges",
    price: 3200,
    originalPrice: 3800,
    stock: 35,
    rating: 4.6,
    reviews: 158,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Canon+725+Toner"],
    description:
      "Canon 725 Black Toner for imageCLASS LBP6000, LBP6020, LBP6030 series. ~1,600 page yield at 5% coverage. Easy twist-and-install, mess-free replacement.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "~1,600 pages @ 5% coverage" },
      { label: "Compatible With", value: "Canon LBP6000, LBP6020, LBP6030" },
      { label: "Part Number", value: "3484B002 (CRG-725)" },
      { label: "Type", value: "Original Canon" },
    ],
  },
  {
    id: "19",
    relatedIds: ["13"],
    name: "Canon C-EXV 18 Black Toner",
    brand: "Canon",
    sku: "CANON-CEXV18",
    category: "Cartridges",
    categorySlug: "cartridges",
    price: 2000,
    originalPrice: 2500,
    stock: 40,
    rating: 4.5,
    reviews: 103,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Canon+C-EXV+18"],
    description:
      "Canon C-EXV 18 Black Toner — for Canon iR1018, iR1022, iR1024 and iR1025 series copiers. ~8,400 page yield. High-capacity, low-cost printing for busy offices.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "~8,400 pages @ 5% coverage" },
      { label: "Compatible With", value: "Canon iR1018/1022/1024/1025" },
      { label: "Part Number", value: "0386B002 (C-EXV18)" },
      { label: "Type", value: "Original Canon" },
    ],
  },
  {
    id: "27",
    relatedIds: ["26"],
    name: "Ricoh MPC2503 Toner Set (4 Colours)",
    brand: "Ricoh",
    sku: "RICOH-MPC2503-SET",
    category: "Cartridges",
    categorySlug: "cartridges",
    price: 3300,
    originalPrice: 4200,
    stock: 22,
    rating: 4.7,
    reviews: 88,
    badge: "Sale",
    badgeColor: "bg-brand text-brand-foreground",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Ricoh+MPC2503+Toner"],
    description:
      "Ricoh MPC2503 Colour Toner — compatible with Ricoh MPC2003, MPC2503, MPC2011 series. Choose Black, Cyan, Magenta, or Yellow. Vivid colour output, long life.",
    specs: [
      { label: "Colours", value: "Black / Cyan / Magenta / Yellow" },
      { label: "Black Yield", value: "~9,500 pages" },
      { label: "CMY Yield", value: "~5,500 pages each" },
      { label: "Compatible With", value: "Ricoh MPC2003/2503/2011" },
      { label: "Type", value: "Compatible Toner" },
    ],
  },
  {
    id: "28",
    relatedIds: ["12"],
    name: "Brother TN-2380 High Yield Black Toner",
    brand: "Brother",
    sku: "BRO-TN2380",
    category: "Cartridges",
    categorySlug: "cartridges",
    price: 4500,
    originalPrice: 5500,
    stock: 25,
    rating: 4.7,
    reviews: 74,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Brother+TN-2380"],
    description:
      "Brother TN-2380 High Yield Black Toner — ~2,600 page yield. For Brother HL-L2300D, HL-L2305W, HL-L2320D, HL-L2340DW and MFC/DCP compatible models.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "~2,600 pages (high yield)" },
      { label: "Compatible With", value: "Brother HL-L2300D/L2320D/L2340DW" },
      { label: "Part Number", value: "TN-2380" },
      { label: "Type", value: "Original Brother" },
    ],
  },
  {
    id: "29",
    relatedIds: ["10"],
    name: "Epson T664 Ink Bottle Set (4 Colours)",
    brand: "Epson",
    sku: "EPS-T664-SET",
    category: "Cartridges",
    categorySlug: "cartridges",
    price: 3600,
    originalPrice: 4400,
    stock: 40,
    rating: 4.7,
    reviews: 92,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Epson+T664+Ink+Set"],
    description:
      "Epson T664 EcoTank Ink Bottle Set — Black, Cyan, Magenta, Yellow. Designed for Epson L-series EcoTank printers. Up to 4,000 black and 6,500 colour pages per bottle.",
    specs: [
      { label: "Colours", value: "Black, Cyan, Magenta, Yellow" },
      { label: "Black Yield", value: "~4,000 pages" },
      { label: "Colour Yield", value: "~6,500 pages per colour" },
      { label: "Compatible With", value: "Epson L110, L120, L210, L3150, L3250" },
      { label: "Volume", value: "70ml Black, 70ml each CMY" },
    ],
  },
  {
    id: "30",
    name: "Kyocera TK-1170 Black Toner",
    brand: "Kyocera",
    sku: "KYO-TK1170",
    category: "Cartridges",
    categorySlug: "cartridges",
    price: 4800,
    originalPrice: 5500,
    stock: 17,
    rating: 4.6,
    reviews: 49,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Kyocera+TK-1170"],
    description:
      "Kyocera TK-1170 Black Toner — for Kyocera ECOSYS M2040dn, M2540dn, and M2640idw. ~7,200 page yield. Kyocera long-life components mean fewer replacements and lower cost.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "~7,200 pages @ 5% coverage" },
      { label: "Compatible With", value: "Kyocera M2040dn, M2540dn, M2640idw" },
      { label: "Part Number", value: "1T02S50NL0" },
      { label: "Type", value: "Original Kyocera" },
    ],
  },

  // ── ACCESSORIES ─────────────────────────────────────────────────────────────
  {
    id: "20",
    name: 'HP Laptop Bag 15.6" Topload',
    brand: "HP",
    sku: "HP-BAG-156-TL",
    category: "Accessories",
    categorySlug: "accessories",
    price: 2200,
    originalPrice: 2800,
    stock: 50,
    rating: 4.4,
    reviews: 211,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+Laptop+Bag"],
    description:
      "HP 15.6\" Topload Laptop Bag — padded compartment, organiser pocket, and ergonomic shoulder strap. Water-resistant material for everyday commutes in Nairobi.",
    specs: [
      { label: "Fits", value: "Up to 15.6\" laptops" },
      { label: "Material", value: "Polyester, water-resistant" },
      { label: "Compartments", value: "Main + front organiser" },
      { label: "Strap", value: "Padded shoulder + carry handle" },
      { label: "Colour", value: "Black" },
    ],
  },
  {
    id: "21",
    name: "USB-C Hub 7-in-1 Multiport Adapter",
    brand: "Orico",
    sku: "ORICO-HUB7C",
    category: "Accessories",
    categorySlug: "accessories",
    price: 3200,
    originalPrice: 3900,
    stock: 35,
    rating: 4.5,
    reviews: 128,
    badge: "Popular",
    badgeColor: "bg-blue-600 text-white",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=USB-C+Hub+7-in-1"],
    description:
      "Orico 7-in-1 USB-C Hub — 4K HDMI, 3× USB 3.0, SD/TF card reader, and 87W PD charging. Plug-and-play, no driver. Slim aluminium build.",
    specs: [
      { label: "Ports", value: "HDMI 4K, 3× USB 3.0, SD, TF, USB-C PD" },
      { label: "HDMI", value: "Up to 4K@30Hz" },
      { label: "USB Speed", value: "5Gbps per USB 3.0 port" },
      { label: "PD Charging", value: "Up to 87W passthrough" },
      { label: "Compatibility", value: "MacBook, Windows, ChromeOS" },
      { label: "Material", value: "Aluminium alloy" },
    ],
  },
  {
    id: "22",
    name: "HP X200 Wireless Optical Mouse",
    brand: "HP",
    sku: "HP-MOUSE-X200",
    category: "Accessories",
    categorySlug: "accessories",
    price: 1800,
    originalPrice: 2200,
    stock: 80,
    rating: 4.3,
    reviews: 342,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=HP+Wireless+Mouse"],
    description:
      "HP X200 Wireless Mouse — 1200 DPI, plug-and-play nano-USB receiver, ergonomic design. Up to 12 months battery life. Works on virtually any surface.",
    specs: [
      { label: "Connection", value: "2.4GHz Wireless" },
      { label: "DPI", value: "1200 DPI" },
      { label: "Battery", value: "2× AA (up to 12 months)" },
      { label: "Receiver", value: "Nano USB" },
      { label: "Buttons", value: "3-button with scroll wheel" },
      { label: "Compatibility", value: "Windows, macOS, ChromeOS" },
    ],
  },
  {
    id: "23",
    name: "Targus Adjustable Laptop Stand",
    brand: "Targus",
    sku: "TARG-AWE55GL",
    category: "Accessories",
    categorySlug: "accessories",
    price: 4500,
    originalPrice: 5200,
    stock: 18,
    rating: 4.6,
    reviews: 63,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Targus+Laptop+Stand"],
    description:
      "Targus Adjustable Laptop Stand — 6 height levels to reduce neck and back strain. Compatible with all 11\"–17\" laptops. Folds flat for travel.",
    specs: [
      { label: "Compatible With", value: '11"–17" laptops' },
      { label: "Height Levels", value: "6 adjustable positions" },
      { label: "Material", value: "Aluminium alloy" },
      { label: "Max Load", value: "5 kg" },
      { label: "Weight", value: "380 g" },
    ],
  },
  {
    id: "31",
    name: "Eaton 5E 850VA UPS",
    brand: "Eaton",
    sku: "EATON-5E850",
    category: "Accessories",
    categorySlug: "accessories",
    price: 8000,
    originalPrice: 9500,
    stock: 22,
    rating: 4.5,
    reviews: 76,
    badge: "Popular",
    badgeColor: "bg-blue-600 text-white",
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Eaton+5E+850VA+UPS"],
    description:
      "Eaton 5E 850VA UPS — protects your computer and printer from power surges, brownouts, and outages. 6 outlets with battery backup. Essential for Kenyan power conditions.",
    specs: [
      { label: "Capacity", value: "850VA / 480W" },
      { label: "Outlets", value: "6 (4 battery backed, 2 surge only)" },
      { label: "Backup Time", value: "~8 minutes at full load" },
      { label: "Input Voltage", value: "160–280V AC" },
      { label: "Recharge Time", value: "~4 hours to 90%" },
      { label: "Weight", value: "4.5 kg" },
    ],
  },
  {
    id: "32",
    name: "Belkin USB-C to USB-A Cable 1m",
    brand: "Belkin",
    sku: "BELKIN-CA-1M",
    category: "Accessories",
    categorySlug: "accessories",
    price: 950,
    originalPrice: 1200,
    stock: 120,
    rating: 4.5,
    reviews: 189,
    badge: null,
    images: ["https://placehold.co/600x600/f1f5f9/475569?text=Belkin+USB-C+Cable"],
    description:
      "Belkin USB-C to USB-A braided cable — 60W fast charging and 480Mbps data transfer. Braided nylon withstands 10,000+ bends. Works with any USB-C device.",
    specs: [
      { label: "Length", value: "1 metre" },
      { label: "Charging", value: "Up to 60W" },
      { label: "Data Speed", value: "USB 2.0 — 480Mbps" },
      { label: "Connector A", value: "USB-C" },
      { label: "Connector B", value: "USB-A" },
      { label: "Cable", value: "Braided nylon" },
    ],
  },
];

export const PRODUCTS_BY_ID = Object.fromEntries(PRODUCTS.map((p) => [p.id, p]));

export const FEATURED_PRODUCTS = [
  ...PRODUCTS.filter((p) => p.badge === "Best Seller"),
  ...PRODUCTS.filter((p) => p.badge === "Hot Deal"),
  ...PRODUCTS.filter((p) => p.badge === "Popular"),
].slice(0, 8);

export function calcDiscount(price: number, originalPrice: number | null): number | null {
  if (!originalPrice) return null;
  return Math.round((1 - price / originalPrice) * 100);
}
