import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter: new PrismaPg(pool) });

async function main() {
  console.log('🌱 Seeding database...');

  await prisma.user.upsert({
    where: { email: 'admin@blacktoner.co.ke' },
    update: {},
    create: {
      name: 'Admin',
      email: 'admin@blacktoner.co.ke',
      phone: '0700000000',
      password: 'admin123',
      role: 'admin',
      emailVerified: true,
    },
  });
  console.log('✅ Admin user seeded');

  const [laptops, printers, cartridges, accessories] = await Promise.all([
    prisma.category.upsert({ where: { slug: 'laptops' }, update: {}, create: { name: 'Laptops', slug: 'laptops', description: 'Business, gaming & student laptops' } }),
    prisma.category.upsert({ where: { slug: 'printers' }, update: {}, create: { name: 'Printers', slug: 'printers', description: 'Inkjet, laser & multifunction printers' } }),
    prisma.category.upsert({ where: { slug: 'cartridges' }, update: {}, create: { name: 'Cartridges', slug: 'cartridges', description: 'OEM & compatible ink & toner cartridges' } }),
    prisma.category.upsert({ where: { slug: 'accessories' }, update: {}, create: { name: 'Accessories', slug: 'accessories', description: 'Cables, bags, stands & more' } }),
  ]);
  console.log('✅ Categories seeded');

  const products = [
    // ── LAPTOPS ────────────────────────────────────────────────────────────────
    {
      name: 'Dell Latitude 5540 15.6" Core i5', slug: 'dell-latitude-5540-i5', sku: 'DELL-LAT-5540-I5',
      description: 'The Dell Latitude 5540 is a premium 15.6" business laptop powered by Intel Core i5-1335U. Built to MIL-SPEC durability standards with a Full HD IPS display, 512GB NVMe SSD, and enterprise security features.',
      price: 89000, originalPrice: 98000, costPrice: 72000, stock: 5,
      brand: 'Dell', featured: true, badge: 'New', badgeColor: 'bg-blue-600 text-white', rating: 4.7, reviews: 86,
      relatedSkus: ['HP-BAG-156-TL', 'ORICO-HUB7C', 'HP-MOUSE-X200', 'EATON-5E850'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Dell+Latitude+5540'],
      specs: [{ label: 'Processor', value: 'Intel Core i5-1335U (10 cores)' }, { label: 'RAM', value: '16GB DDR4 3200MHz' }, { label: 'Storage', value: '512GB NVMe SSD' }, { label: 'Display', value: '15.6" FHD IPS Anti-glare' }, { label: 'Battery', value: 'Up to 10 hours' }, { label: 'OS', value: 'Windows 11 Pro' }, { label: 'Weight', value: '1.78 kg' }, { label: 'Warranty', value: '1 Year Dell ProSupport' }],
      categoryId: laptops.id,
    },
    {
      name: 'Lenovo ThinkPad E14 AMD Ryzen 5', slug: 'lenovo-thinkpad-e14-ryzen5', sku: 'LNV-TPE14-R5',
      description: 'ThinkPad E14 Gen 4 — AMD Ryzen 5 powered, MIL-SPEC tested, spill-resistant keyboard, and crisp 14" FHD IPS display. The go-to business laptop for professionals who demand reliability.',
      price: 72000, originalPrice: 82000, costPrice: 58000, stock: 8,
      brand: 'Lenovo', featured: true, badge: 'Sale', badgeColor: 'bg-yellow-400 text-slate-900', rating: 4.5, reviews: 41,
      relatedSkus: ['HP-BAG-156-TL', 'ORICO-HUB7C', 'HP-MOUSE-X200', 'TARG-AWE55GL'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Lenovo+ThinkPad+E14'],
      specs: [{ label: 'Processor', value: 'AMD Ryzen 5 5625U (6 cores)' }, { label: 'RAM', value: '8GB DDR4 (expandable to 16GB)' }, { label: 'Storage', value: '256GB SSD' }, { label: 'Display', value: '14" FHD IPS Anti-glare' }, { label: 'Battery', value: 'Up to 9.5 hours' }, { label: 'OS', value: 'Windows 11 Home' }, { label: 'Weight', value: '1.61 kg' }, { label: 'Warranty', value: '1 Year Lenovo' }],
      categoryId: laptops.id,
    },
    {
      name: 'HP EliteBook 840 G9 14" Core i7', slug: 'hp-elitebook-840-g9-i7', sku: 'HP-EB840-G9-I7',
      description: 'HP EliteBook 840 G9 — the executive flagship. Intel Core i7, 32GB DDR5, 1TB SSD, HP Sure View privacy screen and Wolf Security. The benchmark for enterprise laptops in Kenya.',
      price: 115000, originalPrice: 128000, costPrice: 92000, stock: 4,
      brand: 'HP', featured: true, badge: 'Best Seller', badgeColor: 'bg-yellow-400 text-slate-900', rating: 4.9, reviews: 62,
      relatedSkus: ['HP-BAG-156-TL', 'ORICO-HUB7C', 'HP-MOUSE-X200', 'TARG-AWE55GL'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+EliteBook+840+G9'],
      specs: [{ label: 'Processor', value: 'Intel Core i7-1255U (10 cores)' }, { label: 'RAM', value: '32GB DDR5' }, { label: 'Storage', value: '1TB NVMe SSD' }, { label: 'Display', value: '14" FHD IPS HP Sure View' }, { label: 'Battery', value: 'Up to 12 hours' }, { label: 'OS', value: 'Windows 11 Pro' }, { label: 'Weight', value: '1.38 kg' }, { label: 'Security', value: 'HP Wolf Security, TPM 2.0' }],
      categoryId: laptops.id,
    },
    {
      name: 'ASUS VivoBook 15 Core i3 15.6"', slug: 'asus-vivobook-15-i3', sku: 'ASUS-VB15-I3',
      description: 'Slim, stylish, and budget-friendly. ASUS VivoBook 15 with Intel Core i3, full-HD display, and a fingerprint reader. Perfect for students and home-office use in Kenya.',
      price: 48000, originalPrice: 55000, costPrice: 38000, stock: 14,
      brand: 'ASUS', featured: false, badge: null, badgeColor: null, rating: 4.3, reviews: 109,
      relatedSkus: ['HP-BAG-156-TL', 'HP-MOUSE-X200', 'EATON-5E850', 'BELKIN-CA-1M'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=ASUS+VivoBook+15'],
      specs: [{ label: 'Processor', value: 'Intel Core i3-1115G4' }, { label: 'RAM', value: '8GB DDR4' }, { label: 'Storage', value: '256GB SSD' }, { label: 'Display', value: '15.6" FHD NanoEdge' }, { label: 'Battery', value: 'Up to 8 hours' }, { label: 'OS', value: 'Windows 11 Home' }, { label: 'Weight', value: '1.8 kg' }, { label: 'Extras', value: 'Fingerprint reader, NumberPad' }],
      categoryId: laptops.id,
    },
    {
      name: 'HP 255 G8 AMD Ryzen 3 3250U', slug: 'hp-255-g8-ryzen3', sku: 'HP-255-G8-R3',
      description: 'HP 255 G8 — best value business laptop in Kenya. AMD Ryzen 3 processor, 8GB RAM, and a full-HD display. Reliable, portable, and built for daily professional use.',
      price: 52000, originalPrice: 58000, costPrice: 42000, stock: 12,
      brand: 'HP', featured: false, badge: 'Popular', badgeColor: 'bg-blue-600 text-white', rating: 4.4, reviews: 134,
      relatedSkus: ['HP-BAG-156-TL', 'HP-MOUSE-X200', 'EATON-5E850', 'TARG-AWE55GL'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+255+G8'],
      specs: [{ label: 'Processor', value: 'AMD Ryzen 3 3250U (2 cores)' }, { label: 'RAM', value: '8GB DDR4' }, { label: 'Storage', value: '256GB SSD' }, { label: 'Display', value: '15.6" FHD Anti-glare' }, { label: 'Battery', value: 'Up to 8.5 hours' }, { label: 'OS', value: 'Windows 11 Home' }, { label: 'Weight', value: '1.74 kg' }, { label: 'Warranty', value: '1 Year HP' }],
      categoryId: laptops.id,
    },
    {
      name: 'HP Pavilion 15 Core i5 12th Gen', slug: 'hp-pavilion-15-i5-12th', sku: 'HP-PAV15-I5-12',
      description: 'HP Pavilion 15 with 12th Gen Intel Core i5 — balanced performance, vibrant display, and long battery life. A great all-rounder for work and home.',
      price: 68000, originalPrice: null, costPrice: 55000, stock: 10,
      brand: 'HP', featured: true, badge: null, badgeColor: null, rating: 4.6, reviews: 88,
      relatedSkus: ['HP-BAG-156-TL', 'ORICO-HUB7C', 'HP-MOUSE-X200', 'TARG-AWE55GL'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+Pavilion+15'],
      specs: [{ label: 'Processor', value: 'Intel Core i5-1235U (10 cores)' }, { label: 'RAM', value: '8GB DDR4' }, { label: 'Storage', value: '512GB SSD' }, { label: 'Display', value: '15.6" FHD IPS' }, { label: 'Battery', value: 'Up to 9 hours' }, { label: 'OS', value: 'Windows 11 Home' }, { label: 'Weight', value: '1.74 kg' }, { label: 'GPU', value: 'Intel Iris Xe Graphics' }],
      categoryId: laptops.id,
    },
    {
      name: 'MacBook Air M2 13" 8GB/256GB', slug: 'macbook-air-m2-8gb', sku: 'APPLE-MBA-M2-8',
      description: 'Apple MacBook Air M2 — fanless, featherlight, up to 18 hours battery. The M2 chip delivers desktop-class performance in the thinnest MacBook ever made.',
      price: 148000, originalPrice: 162000, costPrice: 120000, stock: 3,
      brand: 'Apple', featured: true, badge: 'Hot Deal', badgeColor: 'bg-red-500 text-white', rating: 5.0, reviews: 204,
      relatedSkus: ['ORICO-HUB7C', 'TARG-AWE55GL', 'BELKIN-CA-1M', 'HP-MOUSE-X200'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=MacBook+Air+M2'],
      specs: [{ label: 'Chip', value: 'Apple M2 (8-core CPU, 8-core GPU)' }, { label: 'RAM', value: '8GB Unified Memory' }, { label: 'Storage', value: '256GB SSD' }, { label: 'Display', value: '13.6" Liquid Retina, 2560×1664' }, { label: 'Battery', value: 'Up to 18 hours' }, { label: 'OS', value: 'macOS Ventura' }, { label: 'Weight', value: '1.24 kg' }, { label: 'Ports', value: '2× USB-C (Thunderbolt), MagSafe 3' }],
      categoryId: laptops.id,
    },
    {
      name: 'Lenovo IdeaPad 3 AMD Ryzen 5 5500U', slug: 'lenovo-ideapad-3-ryzen5', sku: 'LNV-IP3-R5-5500',
      description: 'Lenovo IdeaPad 3 — AMD Ryzen 5 performance for everyday use. Backlit keyboard, Wi-Fi 6, and a 15.6" FHD display.',
      price: 62000, originalPrice: 70000, costPrice: 50000, stock: 9,
      brand: 'Lenovo', featured: false, badge: null, badgeColor: null, rating: 4.5, reviews: 78,
      relatedSkus: ['HP-BAG-156-TL', 'ORICO-HUB7C', 'HP-MOUSE-X200', 'EATON-5E850'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Lenovo+IdeaPad+3'],
      specs: [{ label: 'Processor', value: 'AMD Ryzen 5 5500U (6 cores)' }, { label: 'RAM', value: '8GB DDR4 (expandable)' }, { label: 'Storage', value: '512GB SSD' }, { label: 'Display', value: '15.6" FHD IPS Anti-glare' }, { label: 'Battery', value: 'Up to 7.5 hours' }, { label: 'OS', value: 'Windows 11 Home' }, { label: 'Weight', value: '1.65 kg' }, { label: 'Extras', value: 'Backlit keyboard, Wi-Fi 6' }],
      categoryId: laptops.id,
    },

    // ── PRINTERS ───────────────────────────────────────────────────────────────
    {
      name: 'HP LaserJet Pro M404n Mono', slug: 'hp-laserjet-pro-m404n', sku: 'HP-LJ-M404N',
      description: 'HP LaserJet Pro M404n — blazing 40ppm monochrome output with built-in Ethernet. 80,000-page monthly duty cycle. The office workhorse trusted by Kenyan businesses.',
      price: 28500, originalPrice: 33000, costPrice: 22000, stock: 12,
      brand: 'HP', featured: true, badge: 'Best Seller', badgeColor: 'bg-yellow-400 text-slate-900', rating: 4.8, reviews: 124,
      relatedSkus: ['HP-CE285A', 'HP-Q2612A', 'EATON-5E850'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+LaserJet+M404n'],
      specs: [{ label: 'Print Speed', value: 'Up to 40 ppm' }, { label: 'Resolution', value: '1200 × 1200 dpi' }, { label: 'Connectivity', value: 'Ethernet, USB 2.0' }, { label: 'Duty Cycle', value: 'Up to 80,000 pages/month' }, { label: 'Paper Capacity', value: '350 sheets' }, { label: 'Duplex', value: 'Manual' }, { label: 'Weight', value: '7.44 kg' }],
      categoryId: printers.id,
    },
    {
      name: 'Canon PIXMA G2410 Ink Tank MFP', slug: 'canon-pixma-g2410', sku: 'CANON-G2410',
      description: 'Canon PIXMA G2410 — refillable ink tank means ultra-low cost per page. Print, copy, and scan. Up to 7,600 black pages from one ink refill.',
      price: 19500, originalPrice: 22500, costPrice: 15500, stock: 20,
      brand: 'Canon', featured: true, badge: null, badgeColor: null, rating: 4.6, reviews: 57,
      relatedSkus: ['EATON-5E850', 'ORICO-HUB7C'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Canon+PIXMA+G2410'],
      specs: [{ label: 'Functions', value: 'Print, Copy, Scan' }, { label: 'Print Speed', value: '8.8 ipm (B&W), 5 ipm (Colour)' }, { label: 'Resolution', value: '4800 × 1200 dpi' }, { label: 'Connectivity', value: 'USB 2.0' }, { label: 'Black Yield', value: '~7,600 pages' }, { label: 'Colour Yield', value: '~7,700 pages' }],
      categoryId: printers.id,
    },
    {
      name: 'Epson EcoTank L3250 Wi-Fi AIO', slug: 'epson-ecotank-l3250', sku: 'EPS-L3250',
      description: 'Epson EcoTank L3250 — print wirelessly from your phone. Enough ink for 7,500 colour pages included in-box. No cartridge stress, ever.',
      price: 24000, originalPrice: 27500, costPrice: 19000, stock: 15,
      brand: 'Epson', featured: true, badge: 'Popular', badgeColor: 'bg-blue-600 text-white', rating: 4.7, reviews: 98,
      relatedSkus: ['EPS-T664-SET', 'EATON-5E850'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Epson+EcoTank+L3250'],
      specs: [{ label: 'Functions', value: 'Print, Copy, Scan' }, { label: 'Connectivity', value: 'Wi-Fi, Wi-Fi Direct, USB' }, { label: 'Print Speed', value: '10 ipm (B&W), 5 ipm (Colour)' }, { label: 'Resolution', value: '5760 × 1440 dpi' }, { label: 'Black Yield', value: '~4,500 pages' }, { label: 'Colour Yield', value: '~7,500 pages' }],
      categoryId: printers.id,
    },
    {
      name: 'HP Color LaserJet Pro M479fdw', slug: 'hp-color-laserjet-m479fdw', sku: 'HP-CLJP-M479FDW',
      description: 'HP Color LaserJet Pro M479fdw — all-in-one colour laser with fax, auto duplex, and Wi-Fi. 28ppm in full colour.',
      price: 62000, originalPrice: 72000, costPrice: 50000, stock: 6,
      brand: 'HP', featured: false, badge: 'Sale', badgeColor: 'bg-yellow-400 text-slate-900', rating: 4.8, reviews: 44,
      relatedSkus: ['HP-W1510A', 'HP-CE285A', 'EATON-5E850'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+Color+LJ+M479'],
      specs: [{ label: 'Functions', value: 'Print, Copy, Scan, Fax' }, { label: 'Print Speed', value: '28 ppm (colour & mono)' }, { label: 'Resolution', value: '600 × 600 dpi' }, { label: 'Connectivity', value: 'Wi-Fi, Ethernet, USB' }, { label: 'Paper Capacity', value: '300 sheets' }, { label: 'Duplex', value: 'Automatic' }],
      categoryId: printers.id,
    },
    {
      name: 'Brother HL-L2350DW Wi-Fi Laser', slug: 'brother-hl-l2350dw', sku: 'BRO-HLL2350DW',
      description: 'Brother HL-L2350DW — compact wireless monochrome laser printer. Auto duplex and mobile printing via Wi-Fi Direct.',
      price: 18500, originalPrice: 21000, costPrice: 14500, stock: 22,
      brand: 'Brother', featured: false, badge: null, badgeColor: null, rating: 4.5, reviews: 81,
      relatedSkus: ['BRO-TN2380', 'EATON-5E850'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Brother+HL-L2350DW'],
      specs: [{ label: 'Print Speed', value: 'Up to 32 ppm' }, { label: 'Resolution', value: '2400 × 600 dpi' }, { label: 'Connectivity', value: 'Wi-Fi, Wi-Fi Direct, USB' }, { label: 'Duplex', value: 'Automatic' }, { label: 'Paper Capacity', value: '250 sheets' }, { label: 'Weight', value: '7.5 kg' }],
      categoryId: printers.id,
    },
    {
      name: 'Canon imageCLASS LBP6030 Laser', slug: 'canon-imageclass-lbp6030', sku: 'CANON-LBP6030',
      description: 'Canon imageCLASS LBP6030 — compact and affordable mono laser for home and small offices. Quick first print, silent mode, and low running costs.',
      price: 14500, originalPrice: 16500, costPrice: 11000, stock: 30,
      brand: 'Canon', featured: false, badge: null, badgeColor: null, rating: 4.3, reviews: 136,
      relatedSkus: ['CANON-CRG725', 'CANON-CEXV18', 'EATON-5E850'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Canon+LBP6030'],
      specs: [{ label: 'Print Speed', value: 'Up to 18 ppm' }, { label: 'Resolution', value: '2400 × 600 dpi' }, { label: 'Connectivity', value: 'USB 2.0' }, { label: 'Paper Capacity', value: '150 sheets' }, { label: 'First Print', value: '7.8 seconds' }, { label: 'Weight', value: '4.6 kg' }],
      categoryId: printers.id,
    },
    {
      name: 'HP LaserJet Pro M15w Wi-Fi Mono', slug: 'hp-laserjet-m15w', sku: 'HP-LJ-M15W',
      description: "HP LaserJet Pro M15w — the world's smallest laser printer. Print wirelessly from any device via Wi-Fi.",
      price: 13500, originalPrice: 15500, costPrice: 10000, stock: 25,
      brand: 'HP', featured: false, badge: null, badgeColor: null, rating: 4.4, reviews: 91,
      relatedSkus: ['HP-CE285A', 'HP-Q2612A', 'EATON-5E850'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+LaserJet+M15w'],
      specs: [{ label: 'Print Speed', value: 'Up to 19 ppm' }, { label: 'Resolution', value: '600 × 600 dpi' }, { label: 'Connectivity', value: 'Wi-Fi, USB' }, { label: 'Paper Capacity', value: '150 sheets' }, { label: 'Duty Cycle', value: 'Up to 8,000 pages/month' }, { label: 'Weight', value: '4.71 kg' }],
      categoryId: printers.id,
    },
    {
      name: 'Ricoh SP 150w Wireless Laser', slug: 'ricoh-sp-150w', sku: 'RICOH-SP150W',
      description: 'Ricoh SP 150w — compact wireless laser printer with a low total cost of ownership.',
      price: 14000, originalPrice: 16000, costPrice: 11000, stock: 18,
      brand: 'Ricoh', featured: false, badge: null, badgeColor: null, rating: 4.3, reviews: 54,
      relatedSkus: ['RICOH-MPC2503-SET', 'EATON-5E850'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Ricoh+SP+150w'],
      specs: [{ label: 'Print Speed', value: 'Up to 22 ppm' }, { label: 'Resolution', value: '1200 × 600 dpi' }, { label: 'Connectivity', value: 'Wi-Fi, USB 2.0' }, { label: 'Paper Capacity', value: '150 sheets' }, { label: 'Duty Cycle', value: 'Up to 10,000 pages/month' }, { label: 'Weight', value: '5.2 kg' }],
      categoryId: printers.id,
    },

    // ── CARTRIDGES ─────────────────────────────────────────────────────────────
    {
      name: 'HP 85A Black Toner (CE285A) Original', slug: 'hp-85a-toner-ce285a', sku: 'HP-CE285A',
      description: 'HP 85A Original Black LaserJet Toner — for HP LaserJet Pro P1102, M1132, M1212nf MFP. ~1,600 page yield.',
      price: 5500, originalPrice: 6500, costPrice: 4000, stock: 60,
      brand: 'HP', featured: true, badge: 'Best Seller', badgeColor: 'bg-yellow-400 text-slate-900', rating: 4.8, reviews: 317,
      relatedSkus: ['HP-LJ-M404N', 'HP-LJ-M15W'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+85A+Toner'],
      specs: [{ label: 'Colour', value: 'Black' }, { label: 'Page Yield', value: '~1,600 pages @ 5% coverage' }, { label: 'Compatible With', value: 'HP LJ Pro P1102, M1132, M1212nf' }, { label: 'Part Number', value: 'CE285A' }, { label: 'Type', value: 'Original HP' }],
      categoryId: cartridges.id,
    },
    {
      name: 'HP 12A Black Toner (Q2612A) Original', slug: 'hp-12a-toner-q2612a', sku: 'HP-Q2612A',
      description: 'HP 12A Original LaserJet Toner — for HP LaserJet 1010, 1012, 1015, 1018, 1020 series. ~2,000 page yield.',
      price: 5000, originalPrice: 5800, costPrice: 3700, stock: 45,
      brand: 'HP', featured: false, badge: null, badgeColor: null, rating: 4.7, reviews: 228,
      relatedSkus: ['HP-LJ-M404N', 'HP-LJ-M15W'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+12A+Toner'],
      specs: [{ label: 'Colour', value: 'Black' }, { label: 'Page Yield', value: '~2,000 pages @ 5% coverage' }, { label: 'Compatible With', value: 'HP LJ 1010, 1012, 1015, 1018, 1020, 3050' }, { label: 'Part Number', value: 'Q2612A' }, { label: 'Type', value: 'Original HP' }],
      categoryId: cartridges.id,
    },
    {
      name: 'HP 151A Black LaserJet Toner (W1510A)', slug: 'hp-151a-toner-w1510a', sku: 'HP-W1510A',
      description: 'HP 151A Black Original LaserJet Toner — for HP LaserJet Pro 4001, 4002 and MFP 4101, 4102 series. ~3,500 page yield.',
      price: 13000, originalPrice: null, costPrice: 9500, stock: 20,
      brand: 'HP', featured: false, badge: 'New', badgeColor: 'bg-blue-600 text-white', rating: 4.8, reviews: 67,
      relatedSkus: ['HP-LJ-M404N', 'HP-CLJP-M479FDW'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+151A+Toner'],
      specs: [{ label: 'Colour', value: 'Black' }, { label: 'Page Yield', value: '~3,500 pages @ 5% coverage' }, { label: 'Compatible With', value: 'HP LJ Pro 4001n/dn, MFP 4101fdw' }, { label: 'Part Number', value: 'W1510A' }, { label: 'Type', value: 'Original HP' }],
      categoryId: cartridges.id,
    },
    {
      name: 'Samsung MLT-D101S Black Toner', slug: 'samsung-mlt-d101s', sku: 'SAM-MLT-D101S',
      description: 'Samsung MLT-D101S — for Samsung ML-2160, ML-2165W, SCX-3400/3405 series. ~1,500 page yield.',
      price: 10000, originalPrice: 12000, costPrice: 7500, stock: 18,
      brand: 'Samsung', featured: false, badge: 'Hot Deal', badgeColor: 'bg-red-500 text-white', rating: 4.6, reviews: 142,
      relatedSkus: [],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Samsung+MLT-D101S'],
      specs: [{ label: 'Colour', value: 'Black' }, { label: 'Page Yield', value: '~1,500 pages @ 5% coverage' }, { label: 'Compatible With', value: 'Samsung ML-2160, ML-2165W, SCX-3400/3405' }, { label: 'Part Number', value: 'MLT-D101S/ELS' }, { label: 'Type', value: 'Original Samsung' }],
      categoryId: cartridges.id,
    },
    {
      name: 'Canon 725 Black Toner Cartridge', slug: 'canon-725-toner-black', sku: 'CANON-CRG725',
      description: 'Canon 725 Black Toner for imageCLASS LBP6000, LBP6020, LBP6030. ~1,600 page yield. Easy twist-and-install.',
      price: 3200, originalPrice: 3800, costPrice: 2300, stock: 35,
      brand: 'Canon', featured: false, badge: null, badgeColor: null, rating: 4.6, reviews: 158,
      relatedSkus: ['CANON-LBP6030'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Canon+725+Toner'],
      specs: [{ label: 'Colour', value: 'Black' }, { label: 'Page Yield', value: '~1,600 pages @ 5% coverage' }, { label: 'Compatible With', value: 'Canon LBP6000, LBP6020, LBP6030' }, { label: 'Part Number', value: '3484B002 (CRG-725)' }, { label: 'Type', value: 'Original Canon' }],
      categoryId: cartridges.id,
    },
    {
      name: 'Canon C-EXV 18 Black Toner', slug: 'canon-cexv18-toner', sku: 'CANON-CEXV18',
      description: 'Canon C-EXV 18 Black Toner — for Canon iR1018/1022/1024/1025 copiers. ~8,400 page yield.',
      price: 2000, originalPrice: 2500, costPrice: 1500, stock: 40,
      brand: 'Canon', featured: false, badge: null, badgeColor: null, rating: 4.5, reviews: 103,
      relatedSkus: ['CANON-LBP6030'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Canon+C-EXV+18'],
      specs: [{ label: 'Colour', value: 'Black' }, { label: 'Page Yield', value: '~8,400 pages @ 5% coverage' }, { label: 'Compatible With', value: 'Canon iR1018/1022/1024/1025' }, { label: 'Part Number', value: '0386B002 (C-EXV18)' }, { label: 'Type', value: 'Original Canon' }],
      categoryId: cartridges.id,
    },
    {
      name: 'Ricoh MPC2503 Toner Set (4 Colours)', slug: 'ricoh-mpc2503-toner-set', sku: 'RICOH-MPC2503-SET',
      description: 'Ricoh MPC2503 Colour Toner — for Ricoh MPC2003, MPC2503, MPC2011. Choose Black, Cyan, Magenta, or Yellow.',
      price: 3300, originalPrice: 4200, costPrice: 2500, stock: 22,
      brand: 'Ricoh', featured: false, badge: 'Sale', badgeColor: 'bg-yellow-400 text-slate-900', rating: 4.7, reviews: 88,
      relatedSkus: ['RICOH-SP150W'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Ricoh+MPC2503+Toner'],
      specs: [{ label: 'Colours', value: 'Black / Cyan / Magenta / Yellow' }, { label: 'Black Yield', value: '~9,500 pages' }, { label: 'CMY Yield', value: '~5,500 pages each' }, { label: 'Compatible With', value: 'Ricoh MPC2003/2503/2011' }, { label: 'Type', value: 'Compatible Toner' }],
      categoryId: cartridges.id,
    },
    {
      name: 'Brother TN-2380 High Yield Black Toner', slug: 'brother-tn2380-black', sku: 'BRO-TN2380',
      description: 'Brother TN-2380 High Yield Black Toner — ~2,600 page yield. For Brother HL-L2300D/L2320D/L2340DW.',
      price: 4500, originalPrice: 5500, costPrice: 3200, stock: 25,
      brand: 'Brother', featured: false, badge: null, badgeColor: null, rating: 4.7, reviews: 74,
      relatedSkus: ['BRO-HLL2350DW'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Brother+TN-2380'],
      specs: [{ label: 'Colour', value: 'Black' }, { label: 'Page Yield', value: '~2,600 pages (high yield)' }, { label: 'Compatible With', value: 'Brother HL-L2300D/L2320D/L2340DW' }, { label: 'Part Number', value: 'TN-2380' }, { label: 'Type', value: 'Original Brother' }],
      categoryId: cartridges.id,
    },
    {
      name: 'Epson T664 Ink Bottle Set (4 Colours)', slug: 'epson-t664-ink-set', sku: 'EPS-T664-SET',
      description: 'Epson T664 EcoTank Ink Bottle Set — Black, Cyan, Magenta, Yellow. For Epson L-series printers. Up to 4,000 black and 6,500 colour pages.',
      price: 3600, originalPrice: 4400, costPrice: 2600, stock: 40,
      brand: 'Epson', featured: true, badge: null, badgeColor: null, rating: 4.7, reviews: 92,
      relatedSkus: ['EPS-L3250'],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Epson+T664+Ink+Set'],
      specs: [{ label: 'Colours', value: 'Black, Cyan, Magenta, Yellow' }, { label: 'Black Yield', value: '~4,000 pages' }, { label: 'Colour Yield', value: '~6,500 pages per colour' }, { label: 'Compatible With', value: 'Epson L110, L120, L210, L3150, L3250' }, { label: 'Volume', value: '70ml Black, 70ml each CMY' }],
      categoryId: cartridges.id,
    },
    {
      name: 'Kyocera TK-1170 Black Toner', slug: 'kyocera-tk1170-black', sku: 'KYO-TK1170',
      description: 'Kyocera TK-1170 Black Toner — for Kyocera ECOSYS M2040dn, M2540dn, M2640idw. ~7,200 page yield.',
      price: 4800, originalPrice: 5500, costPrice: 3500, stock: 17,
      brand: 'Kyocera', featured: false, badge: null, badgeColor: null, rating: 4.6, reviews: 49,
      relatedSkus: [],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Kyocera+TK-1170'],
      specs: [{ label: 'Colour', value: 'Black' }, { label: 'Page Yield', value: '~7,200 pages @ 5% coverage' }, { label: 'Compatible With', value: 'Kyocera M2040dn, M2540dn, M2640idw' }, { label: 'Part Number', value: '1T02S50NL0' }, { label: 'Type', value: 'Original Kyocera' }],
      categoryId: cartridges.id,
    },

    // ── ACCESSORIES ────────────────────────────────────────────────────────────
    {
      name: 'HP Laptop Bag 15.6" Topload', slug: 'hp-laptop-bag-156', sku: 'HP-BAG-156-TL',
      description: 'HP 15.6" Topload Laptop Bag — padded compartment, organiser pocket, and ergonomic shoulder strap. Water-resistant.',
      price: 2200, originalPrice: 2800, costPrice: 1500, stock: 50,
      brand: 'HP', featured: false, badge: null, badgeColor: null, rating: 4.4, reviews: 211,
      relatedSkus: [],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+Laptop+Bag'],
      specs: [{ label: 'Fits', value: 'Up to 15.6" laptops' }, { label: 'Material', value: 'Polyester, water-resistant' }, { label: 'Compartments', value: 'Main + front organiser' }, { label: 'Strap', value: 'Padded shoulder + carry handle' }, { label: 'Colour', value: 'Black' }],
      categoryId: accessories.id,
    },
    {
      name: 'USB-C Hub 7-in-1 Multiport Adapter', slug: 'usbc-hub-7in1', sku: 'ORICO-HUB7C',
      description: 'Orico 7-in-1 USB-C Hub — 4K HDMI, 3× USB 3.0, SD/TF card reader, and 87W PD charging. Plug-and-play, no driver.',
      price: 3200, originalPrice: 3900, costPrice: 2300, stock: 35,
      brand: 'Orico', featured: true, badge: 'Popular', badgeColor: 'bg-blue-600 text-white', rating: 4.5, reviews: 128,
      relatedSkus: [],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=USB-C+Hub+7-in-1'],
      specs: [{ label: 'Ports', value: 'HDMI 4K, 3× USB 3.0, SD, TF, USB-C PD' }, { label: 'HDMI', value: 'Up to 4K@30Hz' }, { label: 'USB Speed', value: '5Gbps per USB 3.0 port' }, { label: 'PD Charging', value: 'Up to 87W passthrough' }, { label: 'Compatibility', value: 'MacBook, Windows, ChromeOS' }, { label: 'Material', value: 'Aluminium alloy' }],
      categoryId: accessories.id,
    },
    {
      name: 'HP X200 Wireless Optical Mouse', slug: 'hp-wireless-mouse-x200', sku: 'HP-MOUSE-X200',
      description: 'HP X200 Wireless Mouse — 1200 DPI, plug-and-play nano-USB receiver, ergonomic design. Up to 12 months battery life.',
      price: 1800, originalPrice: 2200, costPrice: 1200, stock: 80,
      brand: 'HP', featured: false, badge: null, badgeColor: null, rating: 4.3, reviews: 342,
      relatedSkus: [],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=HP+Wireless+Mouse'],
      specs: [{ label: 'Connection', value: '2.4GHz Wireless' }, { label: 'DPI', value: '1200 DPI' }, { label: 'Battery', value: '2× AA (up to 12 months)' }, { label: 'Receiver', value: 'Nano USB' }, { label: 'Buttons', value: '3-button with scroll wheel' }, { label: 'Compatibility', value: 'Windows, macOS, ChromeOS' }],
      categoryId: accessories.id,
    },
    {
      name: 'Targus Adjustable Laptop Stand', slug: 'targus-laptop-stand', sku: 'TARG-AWE55GL',
      description: 'Targus Adjustable Laptop Stand — 6 height levels to reduce neck and back strain. Compatible with all 11"–17" laptops.',
      price: 4500, originalPrice: 5200, costPrice: 3200, stock: 18,
      brand: 'Targus', featured: false, badge: null, badgeColor: null, rating: 4.6, reviews: 63,
      relatedSkus: [],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Targus+Laptop+Stand'],
      specs: [{ label: 'Compatible With', value: '11"–17" laptops' }, { label: 'Height Levels', value: '6 adjustable positions' }, { label: 'Material', value: 'Aluminium alloy' }, { label: 'Max Load', value: '5 kg' }, { label: 'Weight', value: '380 g' }],
      categoryId: accessories.id,
    },
    {
      name: 'Eaton 5E 850VA UPS', slug: 'eaton-5e-850va-ups', sku: 'EATON-5E850',
      description: 'Eaton 5E 850VA UPS — protects your computer and printer from power surges, brownouts, and outages. Essential for Kenyan power conditions.',
      price: 8000, originalPrice: 9500, costPrice: 6000, stock: 22,
      brand: 'Eaton', featured: false, badge: 'Popular', badgeColor: 'bg-blue-600 text-white', rating: 4.5, reviews: 76,
      relatedSkus: [],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Eaton+5E+850VA+UPS'],
      specs: [{ label: 'Capacity', value: '850VA / 480W' }, { label: 'Outlets', value: '6 (4 battery backed, 2 surge only)' }, { label: 'Backup Time', value: '~8 minutes at full load' }, { label: 'Input Voltage', value: '160–280V AC' }, { label: 'Recharge Time', value: '~4 hours to 90%' }, { label: 'Weight', value: '4.5 kg' }],
      categoryId: accessories.id,
    },
    {
      name: 'Belkin USB-C to USB-A Cable 1m', slug: 'belkin-usbc-cable-1m', sku: 'BELKIN-CA-1M',
      description: 'Belkin USB-C to USB-A braided cable — 60W fast charging and 480Mbps data transfer. 10,000+ bend rating.',
      price: 950, originalPrice: 1200, costPrice: 600, stock: 120,
      brand: 'Belkin', featured: false, badge: null, badgeColor: null, rating: 4.5, reviews: 189,
      relatedSkus: [],
      images: ['https://placehold.co/600x600/f1f5f9/475569?text=Belkin+USB-C+Cable'],
      specs: [{ label: 'Length', value: '1 metre' }, { label: 'Charging', value: 'Up to 60W' }, { label: 'Data Speed', value: 'USB 2.0 — 480Mbps' }, { label: 'Connector A', value: 'USB-C' }, { label: 'Connector B', value: 'USB-A' }, { label: 'Cable', value: 'Braided nylon' }],
      categoryId: accessories.id,
    },
  ];

  for (const p of products) {
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: { price: p.price, originalPrice: p.originalPrice, stock: p.stock, badge: p.badge, badgeColor: p.badgeColor, rating: p.rating, reviews: p.reviews, relatedSkus: p.relatedSkus, specs: p.specs, featured: p.featured },
      create: p,
    });
  }

  console.log(`✅ ${products.length} products seeded`);
  console.log('🎉 Done!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
